const trackData = [
  {
    name: "01",
    station: "Marktplatz",
    index: 0,
    path: require("./assets/01.wav"),
  },
  {
    name: "02",
    station: "Marktplatz",
    index: 1,
    path: require("./assets/02.wav"),
  },
  {
    name: "03",
    station: "Marktplatz",
    index: 2,
    path: require("./assets/03.wav"),
  },
  {
    name: "04",
    station: "Marktplatz",
    index: 3,
    path: require("./assets/04.wav"),
  },
  {
    name: "05",
    station: "Marktplatz",
    index: 4,
    path: require("./assets/05.wav"),
  },
  {
    name: "06",
    station: "Marktplatz - Fußgängerzone",
    index: 5,
    path: require("./assets/06.wav"),
  },
  {
    name: "07",
    station: "Fußgängerzone",
    index: 6,
    path: require("./assets/07.wav"),
  },
  {
    name: "08",
    station: "Fußgängerzone",
    index: 7,
    path: require("./assets/08.wav"),
  },
  {
    name: "09",
    station: "Fußgängerzone",
    index: 8,
    path: require("./assets/09.wav"),
  },
  {
    name: "10",
    station: "Fußgängerzone",
    index: 9,
    path: require("./assets/10.wav"),
  },
  {
    name: "11",
    station: "Fußgängerzone - Zuckerhut",
    index: 10,
    path: require("./assets/11.wav"),
  },
  {
    name: "12",
    station: "Zuckerhut",
    index: 11,
    path: require("./assets/12.wav"),
  },
  {
    name: "13",
    station: "Andreasplatz",
    index: 12,
    path: require("./assets/13.wav"),
  },
  {
    name: "14",
    station: "Andreasplatz",
    index: 13,
    path: require("./assets/14.wav"),
  },
  {
    name: "15",
    station: "Andreasplatz",
    index: 14,
    path: require("./assets/15.wav"),
  },
  {
    name: "16",
    station: "Andreasplatz",
    index: 15,
    path: require("./assets/16.wav"),
  },
  {
    name: "17",
    station: "Andreaspassage",
    index: 16,
    path: require("./assets/17.wav"),
  },
  {
    name: "18",
    station: "Andreaspassage",
    index: 17,
    path: require("./assets/18.wav"),
  },
  {
    name: "19",
    station: "Andreaspassage",
    index: 18,
    path: require("./assets/19.wav"),
  },
  {
    name: "20",
    station: "Andreasplatz",
    index: 19,
    path: require("./assets/20.wav"),
  },
  {
    name: "21",
    station: "Andreasplatz",
    index: 20,
    path: require("./assets/21.wav"),
  },
  {
    name: "22",
    station: "Andreasplatz",
    index: 21,
    path: require("./assets/22.wav"),
  },
  {
    name: "23",
    station: "Andreasplatz - Huckup-Statue",
    index: 22,
    path: require("./assets/23.wav"),
  },
  {
    name: "24",
    station: "Huckup-Statue",
    index: 23,
    path: require("./assets/24.wav"),
  },
  {
    name: "25",
    station: "Schuhstraße",
    index: 24,
    path: require("./assets/25.wav"),
  },
  {
    name: "26",
    station: "Schuhstraße",
    index: 25,
    path: require("./assets/26.wav"),
  },
  {
    name: "27",
    station: "Schuhstraße",
    index: 26,
    path: require("./assets/27.wav"),
  },
  {
    name: "28",
    station: "Hindenburgplatz",
    index: 27,
    path: require("./assets/28.wav"),
  },
  {
    name: "29",
    station: "Küsthardstraße",
    index: 28,
    path: require("./assets/29.wav"),
  },
  {
    name: "30",
    station: "Neustädter Markt",
    index: 29,
    path: require("./assets/30.wav"),
  },
  {
    name: "31",
    station: "Neustädter Markt",
    index: 30,
    path: require("./assets/31.wav"),
  },
  {
    name: "32",
    station: "Neustädter Markt",
    index: 31,
    path: require("./assets/32.wav"),
  },
  {
    name: "33",
    station: "Neustädter Markt - Knollenstraße",
    index: 32,
    path: require("./assets/33.wav"),
  },
  {
    name: "34",
    station: "Knollenstraße",
    index: 33,
    path: require("./assets/34.wav"),
  },
  {
    name: "35",
    station: "Knollenstraße",
    index: 34,
    path: require("./assets/35.wav"),
  },
  {
    name: "36",
    station: "Knollenstraße - Kesslerstraße",
    index: 35,
    path: require("./assets/36.wav"),
  },
  {
    name: "37",
    station: "Kesslerstraße",
    index: 36,
    path: require("./assets/37.wav"),
  },
  {
    name: "38",
    station: "Kesslerstraße",
    index: 37,
    path: require("./assets/38.wav"),
  },
  {
    name: "39",
    station: "Kehrwiederwall",
    index: 38,
    path: require("./assets/39.wav"),
  },
  {
    name: "40",
    station: "Kehrwiederwall",
    index: 39,
    path: require("./assets/40.wav"),
  },
  {
    name: "41",
    station: "Kehrwiederwall",
    index: 40,
    path: require("./assets/41.wav"),
  },
  {
    name: "42",
    station: "Kehrwiederwall",
    index: 41,
    path: require("./assets/42.wav"),
  },
  {
    name: "43",
    station: "Kehrwiederwall - Lappenberg",
    index: 42,
    path: require("./assets/43.wav"),
  },
  {
    name: "44",
    station: "Lappenberg",
    index: 43,
    path: require("./assets/44.wav"),
  },
  {
    name: "45",
    station: "Gelber Stern",
    index: 44,
    path: require("./assets/45.wav"),
  },
  {
    name: "46",
    station: "Brühl",
    index: 45,
    path: require("./assets/46.wav"),
  },
  {
    name: "47",
    station: "Brühl",
    index: 46,
    path: require("./assets/47.wav"),
  },
  {
    name: "48",
    station: "Brühl",
    index: 47,
    path: require("./assets/48.wav"),
  },
  {
    name: "49",
    station: "Brühl",
    index: 48,
    path: require("./assets/49.wav"),
  },
  {
    name: "50",
    station: "Heilig-Kreuz-Kirche - Schuhstraße",
    index: 49,
    path: require("./assets/50.wav"),
  },
  {
    name: "51",
    station: "Schuhstraße",
    index: 50,
    path: require("./assets/51.wav"),
  },
  {
    name: "52",
    station: "Judenstraße",
    index: 51,
    path: require("./assets/52.wav"),
  },
  {
    name: "53",
    station: "Marktplatz",
    index: 52,
    path: require("./assets/53.wav"),
  },
  {
    name: "54",
    station: "Marktplatz",
    index: 53,
    path: require("./assets/54.wav"),
  },
  {
    name: "55",
    station: "Marktplatz",
    index: 54,
    path: require("./assets/55.wav"),
  },
  {
    name: "56",
    station: "Marktplatz",
    index: 55,
    path: require("./assets/56.wav"),
  },
  {
    name: "57",
    station: "Marktplatz",
    index: 56,
    path: require("./assets/57.wav"),
  },
  {
    name: "58",
    station: "Marktplatz",
    index: 57,
    path: require("./assets/58.wav"),
  },
  {
    name: "59",
    station: "Marktplatz",
    index: 58,
    path: require("./assets/59.wav"),
  },
];

export default trackData;
